
rawdir:
    /hpc/cog_bioinf/ridder/users/lchen/Projects/Medaka_t/concall/data/samples/CY_SS_PC_HN_0001_002_000_GU_303_HAC
SUP_SAMPLES:
    CY_SS_PC_HN_0001_002_000_GU_303_HAC

BBTYPE:
    data/seg/bb-C.fa
gz:
    False
ref_genome_final:
    /hpc/cog_bioinf/GENOMES/Cyclomics_reference_genome/version12/Homo_sapiens.GRCh37.GATK.illumina_cyclomics_backbone.fasta
min_insert_length:
    0
max_insert_length:
    300000
