
# Data locations. Change [your path] to where you put the project folder concall/.
rawdir:
    /hpc/cog_bioinf/ridder/users/lchen/Projects/Medaka_t/concall/data/samples/CY_SUP_SAMPLE_TEST2
SUP_SAMPLES:
    TEST_snakemake2
gz:
    True
genome:
    ch37: /hpc/cog_bioinf/GENOMES/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
ref_genome_final:
    /hpc/cog_bioinf/GENOMES/Cyclomics_reference_genome/version12/Homo_sapiens.GRCh37.GATK.illumina_cyclomics_backbone.fasta
BBTYPE:
    data/seg/bb-C.fa
min_insert_length:
    0
max_insert_length:
    300000
