
# Software locations. CHange if needed.
#IN_MEDAKA: "/hpc/cog_bioinf/ridder/users/lchen/miniconda37_2/envs/snake-mdk/bin/activate"
#SOURCE: "source"
rawdir:
#    /hpc/cog_bioinf/ridder/users/lchen/Projects/Medaka_t/concall/data/samples
#    /hpc/cog_bioinf/ridder/nanopore/raw_data/RCA/CY_SM_PC_HC_0002_001_000/fastq_pass/
#    /hpc/cog_bioinf/ridder/nanopore/raw_data/RCA/DER3848/20190822_1411_GA40000_FAK80297_1b8c076d/fastq_pass
    #1. /hpc/cog_bioinf/ridder/nanopore/raw_data/RCA/DER4355/fastq_pass
    /hpc/cog_bioinf/ridder/nanopore/raw_data/RCA/CY_SS_SC_HN_0001_006_000_GU_303_HAC
#samples:
#    b0: /hpc/cog_bioinf/ridder/users/lchen/Projects/Medaka_t/data/Alessio119RCA_guppy_3.0.3_HAC_b0.fastq
SUP_SAMPLES:
    CY_SS_SC_HN_0001_006_000_GU_303_HAC
gz:
    True
#CY_SM_PC_HC_0002_001_000
   

#genome:
#    ch37: /hpc/cog_bioinf/GENOMES/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta

#ref:
#    bb: /hpc/cog_bioinf/ridder/users/lchen/Projects/Medaka_t/data/backbone.fa
#    target: /hpc/cog_bioinf/ridder/users/lchen/Projects/Medaka_t/data/backbone.fatargets.fa
