
rawdir:
    /hpc/cog_bioinf/ridder/users/lchen/Projects/Medaka_t/concall/data/samples/DER4126
SUP_SAMPLES:
    DER4126
 # 5000 reads per fastq file. in der4126, total: 624 files 
gz:
    False
ref_genome_final:
    /hpc/cog_bioinf/GENOMES/Cyclomics_reference_genome/version12/Homo_sapiens.GRCh37.GATK.illumina_cyclomics_backbone.fasta   
BBTYPE:
    data/seg/bb-C.fa
