rawdir:
    /hpc/cog_bioinf/ridder/users/lchen/Projects/Medaka_t/concall/data/samples/DER4535_s0
#    /hpc/cog_bioinf/ridder/nanopore/raw_data/RCA/DER4535/fastq_pass
SUP_SAMPLES:
    DER4535
gz:
    False
ref_genome_final:
    /hpc/cog_bioinf/GENOMES/Cyclomics_reference_genome/version12/Homo_sapiens.GRCh37.GATK.illumina_cyclomics_backbone.fasta   
BBTYPE:
    data/seg/bbcr-G.fa
min_insert_length:
    0
max_insert_length:
    300000
