
# Data locations. Change [your path] to where you put the project folder concall/.
rawdir:
    [your path]/concall/data/samples/CY_SUP_SAMPLE_TEST
SUP_SAMPLES:
    CY_SUP_SAMPLE_TEST 


genome:
    ch37: /hpc/cog_bioinf/GENOMES/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta

#ref:
#    bb: /hpc/cog_bioinf/ridder/users/lchen/Projects/Medaka_t/data/backbone.fa
#    target: /hpc/cog_bioinf/ridder/users/lchen/Projects/Medaka_t/data/targets.fa
