rawdir:
    /home/runner/work/concall/concall/test/test_data/TEST40
SUP_SAMPLES:
    TEST40
gz:
    True
genome:
    /home/runner/work/concall/concall/data/test_ref/test_ref.fasta  
backbone_fa:
    /home/runner/work/concall/concall/data/backbones/BB36.fa
min_insert_length:
    0
max_insert_length:
    300000
3_prime:
     data/seg/3_prime_BB25.fa
5_prime:
     data/seg/5_prime_BB25.fa
mail:
    False
sing:
    False
