
# Data locations. Change [your path] to where you put the project folder concall/.
rawdir:
    /hpc/cog_bioinf/ubec/useq/raw_data/nanopore/DER5087/fastq_pass/
SUP_SAMPLES:
    DER5087-all
read_count_in_a_file:
    10000
gz:
    False
ref_genome_final:
    /hpc/compgen/GENOMES/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
BBTYPE:
    data/seg/bbcr-G.fa
min_insert_length:
    0
max_insert_length:
    300000
mail:
    True
