
# Data locations. Change [your path] to where you put the project folder concall/.
rawdir:
    /hpc/compgen/users/lchen/concall_github/concall/data/samples/TIME1
SUP_SAMPLES:
    TIME1
gz:
    True
genome:
    /hpc/compgen/GENOMES/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
ref_genome_final:
    /hpc/compgen/GENOMES/Cyclomics_reference_genome/version12/Homo_sapiens.GRCh37.GATK.illumina_cyclomics_backbone.fasta
BBTYPE:
    data/seg/bb22-g.fa
min_insert_length:
    0
max_insert_length:
    300000
mail:
    True
3_prime:
    data/seg/3_prime_BB22.fa
5_prime:
    data/seg/5_prime_BB22.fa
