
# Data locations. Change [your path] to where you put the project folder concall/.
rawdir:
    /hpc/compgen/users/lchen/concall/test/test_data/TEST40
SUP_SAMPLES:
    TEST40
gz:
    True
genome:
    /hpc/compgen/GENOMES/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
ref_genome_final:
    /hpc/compgen/GENOMES/Cyclomics_reference_genome/version12/Homo_sapiens.GRCh37.GATK.illumina_cyclomics_backbone.fasta
BBTYPE:
    data/seg/bb-C.fa
min_insert_length:
    0
max_insert_length:
    300000
