
# Data locations. Change [your path] to where you put the project folder concall/.
rawdir:
    /hpc/compgen/nanopore/raw_data/RCA/DER4866/fastq_pass
SUP_SAMPLES:
    DER4866
gz:
    True
genome:
    /hpc/cog_bioinf/GENOMES/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
    #/hpc/cog_bioinf/GENOMES/1KP_GRCh38/GRCh38_full_analysis_set_plus_decoy_hla.fa
#ref_genome_final:
#    /hpc/compgen/GENOMES/Cyclomics_reference_genome/version12/Homo_sapiens.GRCh37.GATK.illumina_cyclomics_backbone.fasta
bb_only_ref:
    data/ref/BB25_ref.fa
BBTYPE:
    data/seg/bb25-g.fa
min_insert_length:
    0
max_insert_length:
    300000
mail:
    True
3_prime:
    data/seg/3_prime_BB25.fa
5_prime:
    data/seg/5_prime_BB25.fa
